export const PROJECTS = [
  {
    id: 1,
    title: "Reproductor de GIFs con API",
    description:
      "Aplicación web que permite reproducir GIFs utilizando una API externa.",
    technologies: ["HTML", "CSS", "JavaScript", "API REST"],
    githubUrl: "https://github.com/KevinDGutierrez/gif-app-kgutierrez.git",
    liveUrl: "https://gif-app-kgutierrez.vercel.app/",
    cover: "/assets/cover_gifplayer.png",
    images: ["/assets/giff1.png", "/assets/giff3.png"],
  },
  {
    id: 2,
    title: "Laboratorio 1 - Estilo Propio",
    description:
      "Reinterpretación y rediseño de un proyecto base, aplicando estilos y creatividad propios para demostrar habilidades de diseño UI/UX y CSS.",
    technologies: ["HTML", "CSS", "Diseño UI/UX"],
    githubUrl: "https://github.com/KevinDGutierrez/PaginaLab1.git",
    liveUrl: "https://pagina-lab1.vercel.app/",
    cover: "/assets/cover_lab1.png",
    images: ["/assets/l1.png", "/assets/l2.png", "/assets/l3.png", "/assets/l4.png", "/assets/l5.png"],
  },
  {
    id: 3,
    title: "Buscador de Pokémon con API",
    description:
      "Aplicación interactiva para buscar y visualizar información detallada de diferentes Pokémon, consumiendo datos de una API especializada.",
    technologies: ["HTML", "CSS", "JavaScript", "PokeAPI"],
    githubUrl: "https://github.com/KevinDGutierrez/PokemonApp-kgutierrez.git",
    liveUrl: "https://pokemon-app-kgutierrez.vercel.app/",
    cover: "/assets/cover_pokemon.png",
    images: ["/assets/poke2.png", "/assets/poke3.png"],
  },
  {
    id: 4,
    title: "Spotify App con API",
    description:
      "Recreación de una interfaz similar a Spotify, permitiendo la exploración de música y artistas mediante la integración con la API de Spotify.",
    technologies: ["HTML", "CSS", "JavaScript", "Spotify API"],
    githubUrl: "https://github.com/KevinDGutierrez/Spotify_kgutierrez-2023455.git",
    liveUrl: "https://spotify-kgutierrez-2023455.vercel.app/",
    cover: "/assets/cover_spotifyapp.png",
    images: ["/assets/s1.png", "/assets/s2.png", "/assets/s3.png", "/assets/s4.png"],
  },
  {
    id: 5,
    title: "Gestor de Tareas Frontend",
    description:
      "Una aplicación frontend para organizar y gestionar tareas diarias. Permite añadir, editar y eliminar tareas de forma intuitiva.",
    technologies: ["HTML", "CSS", "JavaScript", "(LocalStorage)"],
    githubUrl: "https://github.com/KevinDGutierrez/Gestor-de-Tareas-ADASCHOOL.git",
    liveUrl: "https://gestor-de-tareas-adaschool.vercel.app/",
    cover: "/assets/cover_taskmanager.png",
    images: ["/assets/g1.png", "/assets/g2.png", "/assets/g3.png", "/assets/g4.png", "/assets/g5.png", "/assets/g6.png", "/assets/g7.png"],
  },
  {
    id: 6,
    title: "Banking System - Banca Virtual (Full Stack)",
    description:
      "Proyecto grupal Full Stack que simula una banca virtual. Incluye funcionalidades para transferencias y gestión de cuentas, demostrando integración frontend-backend.",
    technologies: ["React", "Node.js", "Express.js", "MongoDB", "JWT", "APIs REST"],
    githubUrl: "https://github.com/KevinDGutierrez/Banking-System-Frontend.git",
    liveUrl: "https://banking-system-frontend-beige.vercel.app/",
    cover: "/assets/cover_banking.png",
    images: [
      "/assets/b1.png", "/assets/b2.png", "/assets/b3.png", "/assets/b4.png", "/assets/b5.png",
      "/assets/b6.png", "/assets/b7.png", "/assets/b8.png", "/assets/b9.png", "/assets/b10.png",
      "/assets/b11.png", "/assets/b12.png", "/assets/b13.png", "/assets/b14.png", "/assets/b15.png",
      "/assets/b16.png", "/assets/b17.png", "/assets/b18.png", "/assets/b19.png",
    ],
  },
  {
  id: 7,
  title: " Sen-IA ChatBOT Inteligente con IA Conectado a tu CRM",
  description:
    "Asistente virtual inteligente potenciado con Inteligencia Artificial en tiempo real, desarrollado y desplegado completamente sobre la infraestructura de Google Cloud. La solución se integra de forma nativa con el CRM Dolibarr y permite a los clientes interactuar directamente desde WhatsApp y una versión web, sin necesidad de pasos adicionales ni intervención manual. El asistente gestiona conversaciones inteligentes capaces de crear tickets de soporte directamente en el CRM, tanto para clientes sin sesión iniciada como para usuarios previamente registrados en la base de datos. Al generarse un ticket, el sistema notifica automáticamente por correo electrónico al responsable del área correspondiente. Además, el asistente identifica intereses comerciales durante la conversación, notifica a asesores o vendedores, crea registros de terceros dentro del CRM y envía catálogos, información de productos o soluciones del portafolio según lo solicitado por el cliente. Todo el flujo de atención, automatización, notificaciones y gestión de datos se ejecuta directamente desde la conversación, convirtiendo al sistema en un asistente verdaderamente inteligente orientado a optimizar la comunicación, la automatización de procesos empresariales y la experiencia del cliente.",
  technologies: [
    "Dolibarr CRM",
    "Node.js",
    "Google Cloud",
    "Inteligencia Artificial",
    "WhatsApp API",
    "Web Chat",
    "Chatbots",
    "APIs REST",
    "Gemini 2.5 flash",
  ],
  githubUrl: null,
  liveUrl: "https://api.whatsapp.com/send/?phone=50223792400&text&type=phone_number&app_absent=0",
  cover: "/assets/cover_senia.png",
  images: [
    "/assets/crm1.png",
    "/assets/crm2.png",
    "/assets/crm3.png",
    "/assets/crm4.png",
    "/assets/crm5.png",
    "/assets/crm6.png",
    "/assets/crm7.png",
    "/assets/crm8.png",
  ],
},
{
  id: 8,
  title: "Sistema de Reporte de Ventas en Campo",
  description:
    "Solución desarrollada para digitalizar y automatizar la gestión comercial y de atención al cliente mediante integración entre formularios web, asistentes inteligentes, correo y CRM. El sistema permite registrar visitas de ventas, identificar clientes existentes o crear nuevos, almacenar contactos, capturar ubicación GPS, generar oportunidades comerciales y registrar eventos de agenda directamente en el CRM. Además, incorpora validaciones para prevenir errores de captura y notificaciones automáticas por correo cuando se detectan inconsistencias. El proyecto fue diseñado para reducir procesos manuales, mejorar la trazabilidad de la operación comercial y centralizar la información en tiempo real dentro del ecosistema empresarial.",
  technologies: [
    "Node.js",
    "Dolibarr CRM",
    "Google Cloud",
    "KoboToolbox",
    "Web Forms",
    "APIs REST",
    "Automatización",
    "Correo automático",
    "GPS"
  ],
  githubUrl: null,
  liveUrl: null,
  demoUrl: null,
  cover: "/assets/cover_kobo.png",
  images: [
    "/assets/kobo1.png",
    "/assets/kobo2.png",
    "/assets/kobo3.png",
    "/assets/kobo4.png",
    "/assets/kobo5.png",
    "/assets/kobo6.png",
    "/assets/kobo7.png"
  ]
},
{
  id: 9,
  title: "Sencom Security News Bot",
  description:
    "Plataforma corporativa de noticias de ciberseguridad potenciada por Gemini 2.5, diseñada para obtener noticias desde Google News, generar resúmenes inteligentes y presentarlas en una interfaz tipo blog. El sistema permite visualizar noticias con resumen y redirección a la fuente original, solicitar auditorías gratuitas y enviar reportes semanales por correo a usuarios o clientes seleccionados. Incluye un panel administrativo con autenticación OAuth 2.0 de Google, desde donde se pueden gestionar contactos, editar noticias, modificar el hero o bienvenida del blog, visualizar solicitudes de auditoría y ejecutar procesos manuales como actualización del blog, generación semanal y envío de reportes. Además, utiliza Google Scheduler para automatizar estas tareas cada lunes. El proyecto también integra un bot especializado para la creación de brochures de SENCOM, donde el usuario solo carga información como datasheets, país, sector objetivo y contactos opcionales, y el sistema genera brochures alineados a los lineamientos corporativos usando Gemini 3 Pro Image Preview.",
  technologies: [
    "React",
    "Node.js",
    "Firebase",
    "Google Cloud",
    "Firebase Hosting",
    "Gemini 2.5 flash",
    "Gemini 3 Pro Image Preview",
    "Google News",
    "Google Scheduler",
    "OAuth 2.0",
    "HTML",
    "CSS",
    "APIs REST",
    "Automatización",
    "Email Reports"
  ],
  githubUrl: null,
  liveUrl: "https://sencom-security-news.web.app",
  cover: "/assets/cover_securitynews.png",
  images: [
    "/assets/Sencom_News (1).png",
    "/assets/Sencom_News (2).png",
    "/assets/Sencom_News (3).png",
    "/assets/Sencom_News (4).png",
    "/assets/Sencom_News (5).png",
    "/assets/Sencom_News (6).png",
    "/assets/Sencom_News (7).png",
    "/assets/Sencom_News (8).png",
    "/assets/Sencom_News (9).png",
    "/assets/Sencom_News (10).png",
    "/assets/Sencom_News (11).png",
    "/assets/Sencom_News (12).png",
    "/assets/Sencom_News (13).png",
    "/assets/Sencom_News (14).png",
    "/assets/Sencom_News (15).png",
    "/assets/Sencom_News (16).png",
    "/assets/Sencom_News (17).png",
    "/assets/Sencom_News (18).png",
    "/assets/Sencom_News (19).png"
  ],
},
{
  id: 10,
  title: "Zenith AI - Plataforma de Prospección Inteligente",
  description:
    "Plataforma beta de prospección inteligente enfocada en Centroamérica, potenciada con Gemini 3 para buscar empresas según el sector de interés, obtener contactos comerciales y guardar leads dentro de una base de datos personal. Incluye un módulo de campañas tipo HubSpot para envío de correos masivos, creación y edición de plantillas, selección de contactos, creación de segmentos y solicitud de remitentes para enviar correos desde diferentes direcciones. La plataforma también cuenta con un módulo de leads para administrar prospectos guardados, opciones de personalización pensadas para marca blanca, configuración de perfil personal y empresarial, y un dashboard con métricas de rendimiento como clics, aperturas de correos y reportes de campañas. Además, incorpora recomendaciones de IA para sugerir prospectos y oportunidades en función de búsquedas recientes. Utiliza autenticación con Google y permisos de Gmail para el envío de correos, con infraestructura desplegada en Google Cloud, frontend en Firebase Hosting y base de datos en Firebase.",
  technologies: [
    "React",
    "Node.js",
    "Firebase",
    "Google Cloud",
    "Firebase Hosting",
    "Gemini 3",
    "Google OAuth",
    "Gmail API",
    "Email Marketing",
    "Prospección B2B",
    "Campañas Masivas",
    "Dashboard Analytics",
    "HTML",
    "CSS",
    "APIs REST",
    "Marca Blanca"
  ],
  githubUrl: null,
  liveUrl: "https://prospeccion-12ca0.web.app",
  cover: "/assets/cover_zenith.png",
  images: [
    "/assets/Zenith (1).png",
    "/assets/Zenith (2).png",
    "/assets/Zenith (3).png",
    "/assets/Zenith (4).png",
    "/assets/Zenith (5).png",
    "/assets/Zenith (6).png",
    "/assets/Zenith (7).png",
    "/assets/Zenith (8).png",
    "/assets/Zenith (9).png",
    "/assets/Zenith (10).png",
    "/assets/Zenith (11).png",
    "/assets/Zenith (12).png",
    "/assets/Zenith (13).png",
    "/assets/Zenith (14).png"
  ],
}
];

export const PROJECTS_IMPROVED = [
  {
    id: 1,
    title: "GIF STUDIO",
    description:
      "Aplicación web que permite buscar y reproducir GIFs utilizando una API externa. Incluye funcionalidades de búsqueda por palabras clave.",
    technologies: ["HTML", "CSS", "JavaScript", "API REST"],
    githubUrl: "https://github.com/KevinDGutierrez/New-Giff-App",
    liveUrl: "https://new-giff-app.vercel.app/",
    cover: "/assets/cover_gifstudio.png",
    images: ["/assets/gif1.png", "/assets/gif2.png"],
  },
  {
    id: 2,
    title: "PokeDex",
    description:
      "Aplicación interactiva para buscar y visualizar información detallada de diferentes Pokémon, consumiendo datos de una API especializada.",
    technologies: ["HTML", "CSS", "JavaScript", "PokeAPI"],
    githubUrl: "https://github.com/KevinDGutierrez/New_Pokedex",
    liveUrl: "https://pokedex-zeta-taupe.vercel.app/",
    cover: "/assets/cover_pokedex.png",
    images: ["/assets/dex.png","/assets/dex2.png","/assets/dex1.png", "/assets/dex3.png"],
  },
  {
    id: 3,
    title: "Spotify",
    description:
      "Recreación de una interfaz similar a Spotify, permitiendo la exploración de música y artistas mediante la integración con la API de Spotify.",
    technologies: ["HTML", "CSS", "JavaScript", "Spotify API"],
    githubUrl: "https://github.com/KevinDGutierrez/New_Spotify",
    liveUrl: "https://new-spotify-zeta.vercel.app/",
    cover: "/assets/cover_newspotify.png",
    images: ["/assets/nsp1.png", "/assets/nsp2.png", "/assets/nsp3.png", "/assets/nsp4.png"],
  }
];

export const SKILLS = [
  { name: 'HTML', icon: 'html5', level: 90 },
  { name: 'CSS', icon: 'css3', level: 85 },
  { name: 'JavaScript', icon: 'javascript', level: 80 },
  { name: 'Java', icon: 'java', level: 75 },
  { name: 'JavaFX', icon: 'https://i.ibb.co/ksx0xvT7/Java-FX-Logo.png', level: 65 },
  { name: 'Axios', icon: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/axios.svg', level: 70 },
  { name: 'GitHub', icon: 'github', level: 88 },
  { name: 'MySQL', icon: 'mysql', level: 78 },
  { name: 'MongoDB', icon: 'mongodb', level: 72 },
  { name: 'Material UI', icon: 'materialui', level: 60 },
  { name: 'Chakra UI', icon: 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/chakraui.svg', level: 55 },
  { name: 'Bootstrap', icon: 'bootstrap', level: 82 },
  { name: 'JWT', icon: 'https://i.ibb.co/1YSYnjhL/jwt-8x.png', level: 68 },
  { name: 'NodeJS', icon: 'nodejs', level: 70 },
  { name: 'React', icon: 'react', level: 65 },
  { name: 'Postman', icon: 'https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg', level: 75 },
  { name: 'Tailwind CSS', icon: 'https://i.ibb.co/KchPGmqS/Tailwind-CSS-Logo-svg.png', level: 60 },
  {
    name: 'CISCO CCNA',
    icon: 'https://i.ibb.co/qMnkkT18/ccna-60017385826812075430382.webp',
    level: 80,
  },
];

export const VALUES = [
  {
    title: 'Responsabilidad',
    description: 'Compromiso total con los plazos y la calidad del código.',
    icon: 'fa-handshake',
  },
  {
    title: 'Creatividad',
    description: 'Búsqueda de soluciones originales a problemas técnicos complejos.',
    icon: 'fa-lightbulb',
  },
  {
    title: 'Innovación',
    description: 'Aprendizaje constante de las últimas tendencias tecnológicas.',
    icon: 'fa-code-branch',
  },
  {
    title: 'Colaboración',
    description: 'Capacidad de integración y aporte en equipos multidisciplinarios.',
    icon: 'fa-users',
  },
  {
    title: 'Profesionalismo',
    description: 'Ética y excelencia en cada interacción laboral.',
    icon: 'fa-star-of-life',
  },
];
